import { ArrayElement } from '../utils';
import { ExtractScraperGeneric } from './scraper';
import { YakabooBookScraper, YakabooBook } from './yakaboo-book';
import { SteamGameScraper, SteamGame } from './steam-game';
import { MyAnimeListAnimeScraper, MyAnimeListAnime } from './myanimelist-anime';
import { IMDBFilmScraper, IMDBFilm } from './imdb-film';
import { ImageScraper, Image } from './any-image';
export declare const SCRAPERS: readonly [YakabooBookScraper, SteamGameScraper, MyAnimeListAnimeScraper, IMDBFilmScraper, ImageScraper];
export type ScrapedData = ExtractScraperGeneric<ArrayElement<typeof SCRAPERS>>;
export type { YakabooBook, SteamGame, MyAnimeListAnime, IMDBFilm, Image };
